services:
  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
      POSTGRES_DB: personen-verwaltung
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"